"""Generated EDA report — ``reports/eda.md``.

This file holds the *measurements*. The judgement that follows from them lives in
``docs/MILESTONE_2_EDA_MEMO.md``, which is written by hand and cites these
numbers. Keeping them apart means a rebuild can never silently rewrite a
conclusion, and a conclusion can never drift from the number it rests on.
"""

from __future__ import annotations

from datetime import UTC, datetime

import pandas as pd

from ..features.target import load_contract, modeling_rows
from ..paths import REPORTS_DIR, relative
from . import analysis, figures


def _table(frame: pd.DataFrame, formatters: dict | None = None) -> list[str]:
    """Render a DataFrame as a GitHub-flavoured Markdown table."""
    formatters = formatters or {}
    columns = list(frame.columns)
    lines = [
        "| " + " | ".join(str(c) for c in [frame.index.name or ""] + columns) + " |",
        "|" + "---|" * (len(columns) + 1),
    ]
    for index, row in frame.iterrows():
        cells = [_default_format(index)]
        for column in columns:
            value = row[column]
            formatter = formatters.get(column)
            cells.append(formatter(value) if formatter else _default_format(value))
        lines.append("| " + " | ".join(cells) + " |")
    return lines


def _default_format(value) -> str:
    if isinstance(value, float):
        return "—" if pd.isna(value) else f"{value:,.2f}"
    if isinstance(value, pd.Timestamp):
        return f"{value:%Y-%m}"
    return "—" if value is None or (isinstance(value, float) and pd.isna(value)) else str(value)


def _pct(value: float) -> str:
    return "—" if pd.isna(value) else f"{value:.1%}"


def _count(value: float) -> str:
    return "—" if pd.isna(value) else f"{int(value):,}"


def render(panel: pd.DataFrame, figure_paths: list[str]) -> str:
    """Build the Markdown EDA report from the built panel."""
    contract = load_contract()
    model = modeling_rows(panel)
    dist = analysis.describe_target(model)

    lines = [
        "# Exploratory data analysis — target and panel",
        "",
        f"Generated {datetime.now(UTC).isoformat(timespec='seconds')} by `chp eda`.",
        "This file is regenerated by the pipeline; do not edit it by hand.",
        "The interpretation of these numbers is in `docs/MILESTONE_2_EDA_MEMO.md`.",
        "",
        "## The frozen target",
        "",
        f"- **Definition:** {contract.describe()}",
        f"- **Frozen:** {contract.frozen_date} (Milestone 2), see `configs/target.yaml`",
        f"- **Modelling rows:** {len(model):,} of {len(panel):,} panel rows",
        f"- **Target window:** {dist.start:%Y-%m} to {dist.end:%Y-%m}",
        "",
        "## Continuous target distribution",
        "",
        f"- mean **{dist.mean:+.3f} pp**, standard deviation **{dist.std:.3f} pp**",
        f"- median **{dist.median:+.3f} pp**, interquartile range **{dist.iqr:.2f} pp**",
        f"- median absolute change **{dist.abs_median:.2f} pp**",
        "",
        "| Quantile | " + " | ".join(f"{p:.1%}" for p in dist.quantiles) + " |",
        "|---|" + "---|" * len(dist.quantiles),
        "| Δg (pp) | " + " | ".join(f"{v:+.2f}" for v in dist.quantiles.values()) + " |",
        "",
        f"![Target distribution]({_figure_link(figure_paths, 'fig01')})",
        "",
        "## Directional class prevalence",
        "",
    ]

    overall = analysis.prevalence_overall(model, contract)
    lines += [
        f"At the frozen threshold of ±{contract.tau:g} pp: "
        + ", ".join(f"**{name} {share:.1%}**" for name, share in overall.items()),
        "",
        "### By year",
        "",
    ]
    by_year = analysis.prevalence_by_year(model, contract)
    by_year.index.name = "Year"
    lines += _table(
        by_year,
        {name: _pct for name in contract.label_names} | {"rows": _count},
    )
    lines += ["", f"![Class prevalence by year]({_figure_link(figure_paths, 'fig02')})", ""]

    lines += ["### By county-volume tier", ""]
    by_tier = analysis.prevalence_by_tier(model, contract)
    by_tier.index.name = "Tier"
    lines += _table(
        by_tier,
        {name: _pct for name in contract.label_names} | {"counties": _count, "rows": _count},
    )
    lines += [
        "",
        "The `stable` band is not a constant fraction of the data: it shrinks as",
        "counties get thinner, because thin-market noise alone exceeds the",
        f"±{contract.tau:g} pp threshold. This is a property of the market, not of the model.",
        "",
        "### Counties with the rarest classes",
        "",
    ]
    by_county = analysis.prevalence_by_county(model, contract).head(10)
    by_county.index.name = "County"
    lines += _table(
        by_county[[*contract.label_names, "smallest_class", "dg_sd", "volume"]],
        {name: _pct for name in contract.label_names} | {"smallest_class": _pct},
    )

    lines += [
        "",
        "## County inclusion rule",
        "",
        f"Counties whose median monthly `homes_sold` is below **{contract.min_homes_sold:g}**",
        "are excluded from modelling. Their rows remain in the panel, flagged by",
        "`is_included`, so nothing is silently deleted.",
        "",
        f"![Volume versus dispersion]({_figure_link(figure_paths, 'fig04')})",
        "",
        "### The excluded counties",
        "",
    ]
    excluded = analysis.excluded_county_dispersion(panel)
    if len(excluded):
        excluded = excluded.set_index("county_name")
        excluded.index.name = "County"
        lines += _table(
            excluded[["volume", "rows", "dg_sd", "dg_abs_median", "dg_max_abs"]],
            {"volume": _count, "rows": _count},
        )
    else:
        lines += ["No county falls below the volume floor.", ""]

    lines += [
        "",
        "### The retained counties, most volatile first",
        "",
    ]
    retained = analysis.county_dispersion(model).head(8).set_index("county_name")
    retained.index.name = "County"
    lines += _table(
        retained[["volume", "tier", "rows", "dg_sd", "dg_max_abs"]],
        {"volume": _count, "rows": _count},
    )

    lines += [
        "",
        f"![County time series]({_figure_link(figure_paths, 'fig03')})",
        "",
        "## Coverage and missingness",
        "",
        "### Lowest price coverage",
        "",
    ]
    coverage = analysis.coverage_summary(panel).head(10).set_index("county_name")
    coverage.index.name = "County"
    lines += _table(
        coverage[["months", "months_with_price", "price_coverage", "labelled_rows", "included"]],
        {"price_coverage": _pct, "labelled_rows": _count, "volume": _count},
    )

    lines += ["", "### Column missingness", ""]
    missing = analysis.missingness(panel).head(10).set_index("column")
    missing.index.name = "Column"
    lines += _table(missing, {"null_rate": _pct, "nulls": _count})

    lines += ["", "### Extreme values against the declared plausible ranges", ""]
    outliers = analysis.feature_outliers(panel).set_index("column")
    outliers.index.name = "Column"
    lines += _table(outliers, {"share": _pct, "extreme_values": _count})

    lines += [
        "",
        "## Seasonality",
        "",
        "`z` is the monthly mean divided by its standard error: how many standard",
        "errors the month sits from zero.",
        "",
    ]
    season = analysis.seasonality(model)
    season.index.name = "Month"
    lines += _table(season, {"rows": _count})
    lines += ["", f"![Seasonality]({_figure_link(figure_paths, 'fig05')})", ""]

    lines += [
        "## Structural breaks",
        "",
        "A descriptive scan: for each candidate month with 12 months either side,",
        "the difference between the mean target after it and before it. This names",
        "*when* the regime turned; it makes no claim about significance or cause.",
        "",
    ]
    shifts = analysis.regime_shifts(model)
    if len(shifts):
        shifts = shifts.set_index("month")
        shifts.index.name = "Month"
        lines += _table(shifts[["mean_before", "mean_after", "shift"]])

    lines += ["", "### Prevalence by mortgage-rate regime", ""]
    rate_bands = analysis.rate_regime_prevalence(model, contract)
    rate_bands.index.name = "30-year rate"
    lines += _table(
        rate_bands,
        {name: _pct for name in contract.label_names} | {"rows": _count},
    )

    lines += [
        "",
        "---",
        "",
        "Figures are written to `reports/figures/`. Findings, decisions and open",
        "risks are recorded in `docs/MILESTONE_2_EDA_MEMO.md`.",
        "",
    ]
    return "\n".join(lines)


def _figure_link(paths: list[str], stem: str) -> str:
    """Resolve a figure path for embedding, relative to reports/."""
    for path in paths:
        if stem in path:
            return path.replace("reports/", "")
    return ""


def build_eda(panel: pd.DataFrame, *, write: bool = True) -> tuple[str, list[str]]:
    """Render every figure and the EDA report. Returns their paths."""
    model = modeling_rows(panel)
    figure_paths = figures.build_all(panel, model) if write else []
    markdown = render(panel, figure_paths)

    path = ""
    if write:
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)
        target = REPORTS_DIR / "eda.md"
        target.write_text(markdown)
        path = relative(target)
    return path, figure_paths
