"""Data dictionary generator.

Declared intent comes from ``configs/columns.yaml``; everything observed —
dtype, null rate, min/median/max — is measured from the built panel. Publishing
them side by side means a column whose reality has drifted from its description
is visible in the document itself rather than only in a failing check.
"""

from __future__ import annotations

from datetime import UTC, datetime

import pandas as pd

from ..paths import DOCS_DIR, relative
from .columns import ColumnSpec, load_columns
from .manifest import load_manifest
from .sources import load_registry


def _format_number(value: float) -> str:
    if pd.isna(value):
        return "—"
    if isinstance(value, float) and abs(value) >= 1000:
        return f"{value:,.0f}"
    if isinstance(value, float):
        return f"{value:,.3g}"
    return f"{value:,}"


def observe(panel: pd.DataFrame, name: str) -> dict[str, str]:
    """Measure a column as it actually exists in the built panel."""
    series = panel[name]
    observed = {
        "dtype": str(series.dtype),
        "null_rate": f"{series.isna().mean():.1%}",
        "min": "—",
        "median": "—",
        "max": "—",
    }

    if pd.api.types.is_numeric_dtype(series) and not pd.api.types.is_bool_dtype(series):
        numeric = pd.to_numeric(series, errors="coerce")
        observed["min"] = _format_number(numeric.min())
        observed["median"] = _format_number(numeric.median())
        observed["max"] = _format_number(numeric.max())
    elif pd.api.types.is_datetime64_any_dtype(series):
        if series.notna().any():
            observed["min"] = f"{series.min():%Y-%m-%d}"
            observed["max"] = f"{series.max():%Y-%m-%d}"
    elif pd.api.types.is_bool_dtype(series):
        observed["median"] = f"{series.mean():.1%} true"
    else:
        observed["min"] = f"{series.nunique():,} distinct"

    return observed


def _bounds_text(spec: ColumnSpec) -> tuple[str, str]:
    hard = f"{spec.hard[0]:g} – {spec.hard[1]:g}" if spec.hard else "—"
    plausible = f"{spec.plausible[0]:g} – {spec.plausible[1]:g}" if spec.plausible else "—"
    return hard, plausible


def render(panel: pd.DataFrame) -> str:
    """Build the Markdown data dictionary for the given panel."""
    specs = load_columns()
    registry = load_registry()
    manifest = load_manifest()

    lines = [
        "# Data dictionary — county-month panel",
        "",
        f"Generated {datetime.now(UTC).isoformat(timespec='seconds')} by `chp build`.",
        "This file is regenerated by the pipeline; do not edit it by hand.",
        "",
        "Declared columns come from `configs/columns.yaml`. Observed statistics are",
        "measured from `data/processed/county_month_panel.parquet` on each build, so",
        "a description that has drifted from reality is visible here.",
        "",
        "## Panel",
        "",
        f"- rows: **{len(panel):,}**, one per `(county_fips, reference_month)`",
        f"- counties: {panel['county_fips'].nunique()}",
        (
            f"- coverage: {panel['reference_month'].min():%Y-%m} to "
            f"{panel['reference_month'].max():%Y-%m}"
        ),
        f"- columns: {panel.shape[1]}",
        "",
        "## Columns",
        "",
        "`hard` bounds failing means a parsing or unit error and fails the build.",
        "`plausible` bounds failing is reported as a warning: extreme but real values,",
        "typically thin low-volume county-months.",
        "",
        "| Column | Source | Unit | Declared hard | Declared plausible | "
        "Observed dtype | Null rate | Min | Median | Max | Meaning |",
        "|---|---|---|---|---|---|---|---|---|---|---|",
    ]

    for name, spec in specs.items():
        if name not in panel.columns:
            continue
        observed = observe(panel, name)
        hard, plausible = _bounds_text(spec)
        lines.append(
            f"| `{name}` | {spec.source} | {spec.unit} | {hard} | {plausible} | "
            f"{observed['dtype']} | {observed['null_rate']} | {observed['min']} | "
            f"{observed['median']} | {observed['max']} | {spec.meaning} |"
        )

    lines += ["", "## Sources", ""]
    for source in registry:
        entry = manifest.get(source.source_id)
        lines += [
            f"### `{source.source_id}`",
            "",
            f"- **Role:** {source.role}",
            f"- **URL:** {source.url}",
            f"- **Licence:** {' '.join(source.license.split())}",
            f"- **Citation:** {' '.join(source.citation.split())}",
        ]
        if source.notes:
            lines.append(f"- **Notes:** {' '.join(source.notes.split())}")
        if entry:
            lines += [
                f"- **Retrieved:** {entry.retrieved_at} via `{entry.acquisition}`",
                f"- **Bytes:** {entry.bytes:,}",
                f"- **SHA-256:** `{entry.sha256}`",
            ]
            if entry.http_last_modified:
                lines.append(f"- **Server Last-Modified:** {entry.http_last_modified}")
        lines.append("")

    return "\n".join(lines)


def write_dictionary(panel: pd.DataFrame) -> str:
    """Render and persist ``docs/DATA_DICTIONARY.md``."""
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    path = DOCS_DIR / "DATA_DICTIONARY.md"
    path.write_text(render(panel))
    return relative(path)
